Abstracción del servicio externo
elagarrigue/AyDS23-Winchester4 pull request #11
Opened 2023-06-01 11:54 UTC by octavioantich

Se remplazo la clase de dominio por la clase "Card"

Se integraron al proyecto los servicios externos asignados

Se mplemento el patrón broker en la integración de los 3 servicios externos.

Se modifico la UI para visualizar los 3 cards.

2023-06-05 02:46 UTC, elagarrigue requested changes
- Actualizar el diagrama
- sacar el "external" del paquete del submodule. 
- Visibilidad de las implementaciones en el submodule.

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/ArtistRepositoryImpl.kt
> +    private val broker: Broker
CardBroker

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/ArtistRepositoryImpl.kt
>      private val artistLocalStorage: ArtistLocalStorage,
cardLocalStorage (o artistCard)

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/ArtistRepositoryImpl.kt
>  class ArtistRepositoryImpl(
internal

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/ArtistRepositoryImpl.kt
>          var artist = artistLocalStorage.getArtistInfoFromDataBase(artistName)
getCards

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/ArtistRepositoryImpl.kt
> +    override fun getArtistByName(artistName: String): Collection<Card>? {
Debería retornar una List no nullable (lista vacía es suficiente)

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/ArtistRepositoryImpl.kt
> +                            saveArtist(cards, artistName)
save cards

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/ArtistRepositoryImpl.kt
> +                        if (cards.isEmpty()) {
If cards.isNOYEmpty

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/ArtistRepositoryImpl.kt
> +                        null
Los proxy deberían catchear la excepciones, sino si uno falla todo falla

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/ArtistRepositoryImpl.kt
revisar indentación

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/external/Broker.kt
> +interface Broker {
CardsBroker

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/external/LasFMProxy.kt
> +            URL_IMAGE_LASTFM,
Definir EmtpyCard (null object pattern), o retornar null y no guardarla en la lista

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/external/LasFMProxy.kt
> +                source = "LastFM",
El source debería ser un enumerado, no hardcodear un literal

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/external/NewYorkTimeProxy.kt
> +internal class NewYorkTimeProxy(private val nYTimesArtist: NYTimesArtistService) : ProxyInterface{
idem comentarios proxy

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/external/Proxy.kt
> +
Eliminar saltos de línea extra

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/external/Proxy.kt
> +interface ProxyInterface {
CardProxy. Nunca usar "interface" somo sufijo

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/external/WkipediaProxy.kt
> +internal class WikipediaProxy(private val wikipediaService: WikipediaService) : ProxyInterface{
idem comentarios proxy

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/local/ArtistLocalStorage.kt
>  interface ArtistLocalStorage {
ArtistCard, o Card

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/local/ArtistLocalStorage.kt
> +    fun getArtistInfoFromDataBase( artist: String): Collection<Card>?
```suggestion
    fun getArtistInfoFromDataBase( artist: String): List<Card>
```

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/local/ArtistLocalStorage.kt
> +    fun getArtistInfoFromDataBase( artist: String): Collection<Card>?
getCards

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/local/sqldb/ArtistLocalStorageImpl.kt
> +             values.put(SOURCE_COLUMN, card.source)
Guardar el ordinal del enumerado

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/local/sqldb/ArtistLocalStorageImpl.kt
> +    override fun saveArtist(card: Collection<Card>, artistName: String) {
saveCards

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/local/sqldb/ArtistTableConstants.kt
>  const val ARTISTS_TABLE = "artists"
cards

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/domain/entities/Card.kt
> +    Null,
Evitar este valor

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/domain/entities/Card.kt
> +    var source: String,
: Source

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/domain/repository/ArtistRepository.kt
> +    fun getArtistByName(artistName: String): Collection<Card>?
List

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/domain/repository/ArtistRepository.kt
>  interface ArtistRepository {
CardsRepository

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/presenter/ArtistDescriptionHelperImpl.kt
>  interface ArtistDescriptionHelper {
Card

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
> +    val artistObservable : Observable<Collection<MoreDetailsUiState>>
card
List<CardUiState>

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/MoreDetailsUiState.kt
>  data class MoreDetailsUiState(
CardUiState (o MoreDetailsUiState y que tenga una propiedad List<CardUiState>)

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
internal class

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
> +            }
No es el mismo nivel de abstracción que el thread, mover a sub función

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
>              val artist=repository.getArtistByName(artistName)
cards

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
> +            if (artist != null) {
not empty, pero si es vacío debe setear el ui state "no results"

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
> +                source = card.source,
Crear un factory que transforme el valor del enum a String, para cumplir con OC

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/view/MoreDetailsView.kt
> +        urlButtonNewYorkTime = findViewById(R.id.openUrlButton3)
No cumple con OC, pq hace referencia a los servicios en particular. Definir card1, 2 y 3 (no pedimos q la view sea dinámica, pero que no se vea afectada si se cambia un servicio por ejemplo)

2023-06-05 02:46 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/view/MoreDetailsView.kt
> +            }
No cumple con open closed. Usar los índices en la lista para setear los valores en cada view.

2023-06-05 02:46 UTC, elagarrigue requested changes
- Actualizar el diagrama
- sacar el "external" del paquete del submodule. 
- Visibilidad de las implementaciones en el submodule.

2023-06-06 11:05 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/ArtistCard.kt
> +    private fun saveCards(card: Collection<Card>, artistName: String){
List no Collection

2023-06-06 11:05 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/local/CardsRepository.kt
> +    fun saveCards(card: Collection<Card>, artistName: String)
List

2023-06-06 11:06 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/ArtistCard.kt
> +    private fun markArtistAsLocal(cards: Collection<Card>) {
List

2023-06-06 11:09 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/external/LasFMProxy.kt
> +        val lastFM = lastFMService.getArtist(artistName)
aca deberia haber una try-catch, que pasa si no hay conexion o el servicio esta caido? No solo puede haber un recupero nullo, puede haber fallas, deben capturar excepciones

2023-06-06 11:09 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/external/NewYorkTimeCardProxy.kt
> +        val newYorkTime = nYTimesArtist.getArtist(artistName)
aca deberia haber una try-catch, que pasa si no hay conexion o el servicio esta caido? No solo puede haber un recupero nullo, puede haber fallas, deben capturar excepciones

2023-06-06 11:09 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/external/WkipediaProxy.kt
> +        val wikipedia = wikipediaService.getArtist(artistName)
aca deberia haber una try-catch, que pasa si no hay conexion o el servicio esta caido? No solo puede haber un recupero nullo, puede haber fallas, deben capturar excepciones

2023-06-06 11:11 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/local/sqldb/ArtistLocalStorageImpl.kt
> +         cards.forEach { card ->
identacion

2023-06-06 11:11 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/repository/local/sqldb/ArtistLocalStorageImpl.kt
> +    override fun saveCards(card: Collection<Card>, artistName: String) {
List

2023-06-06 11:19 UTC, Luchyluz requested changes
Los servicios pueden tener problemas, hay que caputrar esos problemas y resolver de alguna manera.

2023-06-06 20:57 UTC, Luchyluz approved these changes

2023-06-06 21:22 UTC, elagarrigue approved these changes

2023-06-07 10:41 UTC, merged